### ISSUE TITLE
Support node-ant

### ISSUE THREAD

**Issue by nadrees** [kevinohara80/grunt-ant-sfdc#16]
Is there any way to support [node-ant](https://github.com/millermedeiros/node-ant) as an ant implementation? This would make it easier (especially for windows users) to get this up an running. 

It doesn't look like this is using anything to terribly advanced so it should be pretty safe.

**Comment by kevinohara80** [comment]
Sorry, I realize this issue is really old and I'm just getting to it now. If this is still something you're interested it, please send me a PR. I'll happily accept it.
