### ISSUE TITLE
Build is Broken: antDeploy looks for user / pass in global options rather than localc

### ISSUE THREAD

**Issue by gunish** [kevinohara80/grunt-ant-sfdc#17]
antdeploy: {
      options: {
        root: 'deploy/',
        apiVersion: '29.0',
        user: 'gunish.chawla@COMPANYNAME',
        pass: 'PASSWORD',
        token: ''
      },

      dev: {
        option: {
          user: 'gunish.chawla@COMPANYNAME', // This variable is no longer read
          pass: 'PASSWORD', // This variable is no longer read
          token: '' // This variable is not longer read
        },
        pkg: {
          staticresources: ['*']
        }
      }
    },

**Comment by kevinohara80** [comment]
Sorry for the incredibly delayed response. If you're still having an issue, please feel free to re-open.
