### ISSUE TITLE
slow deployment time

### ISSUE THREAD

**Issue by conor909** [kevinohara80/grunt-ant-sfdc#31]
My deployments are taking up to 4 minutes to deploy even though my broadband is quite average.  Are there any ways to debug why it might be taking so long?

**Comment by thegogz** [comment]
Have you checked "Deployment Status" in Salesforce Setup?

The deployment length is impacted by a number of factors including
- No of Unit Tests that run
- If Unit tests do DML 
- Volume of code/metadata being deployed
