### ISSUE TITLE
Failed Login Request?

### ISSUE THREAD

**Issue by befreestudios** [kevinohara80/grunt-ant-sfdc#37]
I've been trying to figure out what is happening here.. I've set everything up using the grunt-compress plugin and my configuration seems to be correct (I've double checked my credentials and everything else). What's interesting is its saying that there was a failure to send request to 'login.salesforce' when I've set test.salesforce as the server. Has anyone seen this error before?? Er.. any idea what might be going on? Could it be that I'm behind a proxy?

Any help is greatly appreciated!! Thanks in advance!!

```BUILD FAILED 
C:\Users\****\****\********\node_modules\grunt-ant-sfdc\tmp\ant\build.xml:15: Failed to login: Failed to send request to https://login.salesforce.com/services/Soap/u/29.0```

My Config...
```
antdeploy: {
      options: {
        version: '37'
      },
      dev1: {
        options: {
          user: '****@****.com.dev01',
          pass: '*******',
          token: '*********',
          serverurl: 'https://test.salesforce.com'
        },
        pkg: {
          staticresource: ['*']
        }
      }
    },
```

**Comment by befreestudios** [comment]
UPDATE: Realized that I had the serverurl property wrong so the correct url was not getting picked up.. but even so I'm still getting the following error...

```BUILD FAILED C:\Users\****\****\********\node_modules\grunt-ant-sfdc\tmp\ant\build.xml:15: Failed to login: Failed to send request to https://test.salesforce.com/services/Soap/u/29.0```

**Comment by kevinohara80** [comment]
I'm not sure what's going on. The configuration seems right to me. What version of the ant tool are you running?

**Comment by befreestudios** [comment]
apache-ant-1.9.7

Yea, it's strange. It's running in a windows environment, on eclipse with the force.com plugin, behind a corporate proxy (ughh). So, I have a feeling it might be because of the proxy, I've set http & https-proxy settings in node, windows and eclipse though as well, so now I'm just stabbing in the dark. Let me know if you have any ideas, I'll be continuing to get to the bottom of it.

Thank You!!  ```disclaimer: I'm a salesforce noob :) ```

**Comment by kevinohara80** [comment]
Just circling back here. I don't really have any other ideas. Your suspicion on the proxy is where I'd start. I'm going to close for now but feel free to open another issue if you find a bug related to this.

**Comment by kevinohara80** [comment]
Hey, take a look at #43. I think you are on to something with the proxy issue. This would need to be handled with some changes to the module to allow for passing in the proxy configuration to Ant.
