### ISSUE TITLE
Add support for existing packages for antdestroy

### ISSUE THREAD

**Issue by mattsones** [kevinohara80/grunt-ant-sfdc#39]
It would be handy to be able to use existing packages for antdestroy.

**Comment by mattsones** [comment]
Does #40 answer this sufficiently?

**Comment by kevinohara80** [comment]
I closed the PR because some of AntDestroy was broken as indicated by the comments on the code. I just merged a fix for those issues so if you want to re-PR this against the fixed code I'm happy to review and merge it.
