### ISSUE TITLE
Ant Destroy task generates incorrect `package` and `destructiveXml` files

### ISSUE THREAD

**Issue by nathanKramer** [kevinohara80/grunt-ant-sfdc#42]
Main problem is that the calls to `buildPackageXml` in the `antdestroy` task are passing the `apiVersion` as the second parameter, when the function expects the package name as the second parameter.

The task also creates a non empty `package.xml` which results in a redundant deploy of the package, before destroying.
Have had a go at fixing with #41

**Comment by kevinohara80** [comment]
Fixed and closed.
