### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by bbaker2** [kevinohara80/grunt-ant-sfdc#43]
This tool is wonderful but is unusable behind a (corporate) firewall. This is easy to fix since ant has a [setproxy](https://ant.apache.org/manual/Tasks/setproxy.html) task.

**Comment by kmx9500655** [comment]
@bbaker2 @kevinohara80 

I was able to connect by adding this block to the antdeploy.build.xml file, witch in turn generates the build.xml in tmp...

```
<target name="proxy">
  <property name="proxy.host" value="[YOUR_PROXY_URL]"/>
  <property name="proxy.port" value="8080"/>
  <property name="proxy.user" value="[YOUR_PROXY_USERNAME]"/>
  <property name="proxy.pass" value="[YOUR_PROXY_PASS]"/>
  <setproxy proxyhost="${proxy.host}" 
                   proxyport="${proxy.port}"
                   proxyuser="${proxy.user}"  
                   proxypassword="${proxy.pass}"/>
</target>
```
Then in the deploy target, have it depend on the above proxy target, like so...
```
<target name="deploy" depends="proxy">
```
This is great, but requires mucking with the files in node_packages. I'd like to automate this, but not sure where to start (sorry kindof a grunt noob). Any ideas?

Thanks!!

**Comment by kevinohara80** [comment]
This wouldn't be hard to add as config options. I'm happy to entertain a PR for this. I'm pretty strapped for time at the moment.

**Comment by bbaker2** [comment]
#51 was created to add this feature. Sorry for the delay.

**Comment by bbaker2** [comment]
Hey, I see this was merged. Guess We can close this issue now. Thanks!
